# -- ==========================================
# -- 1. НАСТРОЙКИ ДОСТУПА И СЕТИ
# -- ==========================================

# -- Разрешаем доступ всем IP
setACL({'0.0.0.0/0', '::/0'})

# -- Слушаем стандартный порт 53 (UDP и TCP)
addLocal("0.0.0.0:53")


# -- ==========================================
# -- 2. ВЫШЕСТОЯЩИЕ DNS (Upstreams)
# -- ==========================================

# -- Мы спрашиваем у Google и Cloudflare через шифрованный канал (DoT - порт 853)
# -- Это защищает  DNS-запросы от прослушки хостером.
newServer({address="1.1.1.1:853", tls="openssl", subjectName="cloudflare-dns.com", validateCertificates=true})
newServer({address="8.8.8.8:853", tls="openssl", subjectName="dns.google", validateCertificates=true})

# -- Кэширование (ускоряет работу, взято из твоего примера)
local pc = newPacketCache(100000, {maxTTL=86400, minTTL=0, temporaryFailureTTL=60, staleTTL=60})
getPool(""):setCache(pc)

# -- ==========================================
# -- 3. ГЛАВНАЯ ЛОГИКА (Перенаправление)
# -- ==========================================

MY_VPS_IP = os.getenv("VPS_IP")

# -- ВАРИАНТ А: "Радикальный" (Проксировать ВСЁ)
# -- Если ты хочешь, чтобы ВЕСЬ веб-трафик шел через твой сервер:
addAction(QTypeRule(DNSQType.A), SpoofAction(MY_VPS_IP))
addAction(QTypeRule(DNSQType.AAAA), SpoofAction(MY_VPS_IP))


# -- ВАРИАНТ Б: "По спискам" (Как в репозитории)


# -- proxy_list = newSuffixMatchNode()
# -- for domain in io.lines("/etc/dnsdist/proxy.txt") do 
# --   proxy_list:add(newDNSName(domain))
# -- end
# -- addAction(QNameSuffixRule(proxy_list), SpoofAction(MY_VPS_IP))


# -- ==========================================
# -- 4. БЛОКИРОВКА РЕКЛАМЫ (Опционально)
# -- ==========================================
# -- Я оставил этот блок, он полезен. 
# -- Блокируем известные трекеры, чтобы они даже не грузились.
addAction(QNameSuffixRule({
    'googlesyndication.com.', 
    'adcolony.com.', 
    'hotjar.com.', 
    'mouseflow.com.', 
    'doubleclick.net.', 
    'media.net.',
    'crm.yandex.ru.',
    'an.yandex.ru.'
}), DropAction())
