version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: main_proxy
    restart: always
    # Включаем режим host, чтобы видеть порт 4443 на сервере
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  dns:
    image: powerdns/dnsdist-19:latest
    container_name: dnsdist
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - VPS_IP=${VPS_IP} 
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    